/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author carlos Aguayo 2ºDAM
 */
public class Componente_validador extends javax.swing.JPanel {
    public String tipo_validacion;
    public boolean validador = false;
    /**
     * Creates new form Componente_validador
     */
    public Componente_validador() {
        initComponents();
    }

    public String getTipo_validacion() {
        return tipo_validacion;
    }

    public void setTipo_validacion(String tipo_validacion) {
        this.tipo_validacion = tipo_validacion;
    }

    public boolean isValidador() {
        return validador;
    }

    public void setValidador(boolean validador) {
        this.validador = validador;
    }
    
      public void validar()
{
    switch(tipo_validacion)
    {  
         case "telefono": 
            if(jtextcomponente.getText().isEmpty()){
                jlabelerror.setText("no puede estar vacio");
            }else if(jtextcomponente.getText().length()==9)
            {
                jlabelerror.setText("tienen que ser 9 numeros");
            }else{jlabelerror.setText("todo correcto");
                  validador = true;
            }
            break;
        
          case "DNI": 
            if(jtextcomponente.getText().isEmpty()){
                jlabelerror.setText("no puede estar vacio");
            }else if(jtextcomponente.getText().length()==9)
            {
                jlabelerror.setText("tienen que ser 9 numeros");
            }else{jlabelerror.setText("todo correcto");
                validador = true;
            }
            break;
            
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtextcomponente = new javax.swing.JTextField();
        jlabelerror = new javax.swing.JLabel();

        jtextcomponente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtextcomponenteFocusLost(evt);
            }
        });
        jtextcomponente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextcomponenteActionPerformed(evt);
            }
        });

        jlabelerror.setText(".....................");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtextcomponente, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(jlabelerror, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jtextcomponente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlabelerror)
                .addContainerGap(47, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtextcomponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextcomponenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextcomponenteActionPerformed

    private void jtextcomponenteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtextcomponenteFocusLost
       validar();
       
    }//GEN-LAST:event_jtextcomponenteFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlabelerror;
    private javax.swing.JTextField jtextcomponente;
    // End of variables declaration//GEN-END:variables
}
